[package]
name = "stm32l4x-flash-read-protect"
version = "0.1.0"
authors = ["Ethan Zhang <bluefurbear@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
probe-rs = "0.8"
clap = "3.0.0-beta.1"
